### ISSUE TITLE
Build fails because of mode_tag

### ISSUE THREAD

**Issue by RambilE** [kewuaa/kwm#16]
When building from latest source, it errors with this message:

```
install
└─ install kwm
   └─ compile exe kwm ReleaseSafe native 1 errors
src/kwm/bar.zig:453:17: error: optional type '?[]const u8' does not support field access
    if (mode_tag.len > 0) {
        ~~~~~~~~^~~~
src/kwm/bar.zig:453:17: note: consider using '.?', 'orelse', or 'if'
referenced by:
    render: src/kwm/bar.zig:175:38
    rwm_listener: src/kwm/context.zig:764:42
    6 reference(s) hidden; use '-freference-trace=8' to see all references
```

This seems to be broken after commit 66e45cf
